debug:
  container_name: sailsSample_debug
  image: agileworks/sails_sample_env
  command: "/bin/sh -l"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample
  ports:
    - "1337:1337"

build:
  container_name: sailsSample_build
  image: agileworks/sails_sample_env
  command: "npm run build"
  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

buildDev:
  container_name: sailsSample_buildDev
  image: agileworks/sails_sample_env
  command: "/bin/sh -l -c 'npm i && npm run build'"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

buildProd:
  container_name: sailsSample_buildProd
  image: agileworks/sails_sample_env
  command: "/bin/sh -l -c 'npm i && npm run prod'"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

test:
  container_name: sailsSample_test
  image: agileworks/sails_sample_env
  command: "/bin/sh -l -c 'npm run test-junit'"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

dev:
  container_name: sailsSample_dev
  image: agileworks/sails_sample_env
  command: "/bin/sh -l -c 'npm start'"
  environment:
    PORT: "1337"
    NODE_ENV: "development"
    DOMAIN_HOST: "localhost:1337"

  ports:
    - "8000:1337"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample

prod:
  container_name: sailsSample_prod
  image: agileworks/sails_sample_env
  command: "/bin/sh -l -c 'npm run build-prod && npm run start-prod'"
  environment:
    PORT: "1337"
    NODE_ENV: "development"
    DOMAIN_HOST: "localhost:1337"

  ports:
    - "1337:1337"

  working_dir: /sailsSample
  volumes:
    - ./:/sailsSample


mysql:
  container_name: mysql
  image: dgraziotin/mysql

  ports:
    - "3306:3306"
  environment:
    MYSQL_ADMIN_PASS: "root"
    MYSQL_USER_NAME: "nodejsSample"
    MYSQL_USER_DB: "nodejsSample"
    MYSQL_USER_PASS: "nodejsSample"
    CREATE_MYSQL_BASIC_USER_AND_DB: "true"

  volumes:
    - ../database:/var/lib/mysql/


ci:
  container_name: ci
  image: killercentury/jenkins-dind
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./.jenkins:/var/lib/jenkins
  ports:
    - "5000:5000"
    - "8080:8080"
  privileged: true
